### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jontio**
I also allowed the range of the soft bits to go a bit higher. So nominally soft bits are 75% of what they were. I'm not sure if this is better or not but it might be. Either way testing soft and hard decisions wrt BER, the difference is really had to tell. The demodulators and for the burst signals the freq/timing estimators start to fail before hard decisions fail. I just managed to see a little improvement in 10500 L band signals with really low SNR but had to reduce the signal threshold and the tracking was struggling by that point.

### CODE REVIEW

**Comment by jeroenbeijer** [comment]
Hi Jonti. I merged and pulled the changes in. The results were a little unexpected though. It seems that the multiplication with .75 on the MSK burst symbols has a negative effect. On my "reference" test file the number of decodes dropped by 5 messages. Strangely when I changed this multiplication factor to 1.20 the number of decoded messages increased by 3. For the 10.5k bursts the differences were less clear, on a 20 minute test file I decoded 66 messages with the 0.75 multiplication and 67 without. 

Changing the threshold on the MSK burst detector had a negative affect. I struggled a bit with false positives in the trident detector and it could be that this now triggers during an ongoing burst. There is a difference in how the "top" part of the preamble looks between the MSK and OQPSK bursts. The MSK top part looks like a three pronged fork rather than the 2 prongs in OQPSK. I suppose this may be because of the even spread of 0-1 symbols causing the center frequency to also show in the FFT. What I wanted to do but not got around is to have the MSK burst demodulator be aware of the data carrier presence so that it would not accidentally trigger the start of a burst while there is a burst ongoing. I have added this code for the regular MSK demodulator which I am working on now. I will see if I can implement this so that changing the threshold does not cause false positives in the burst detection. I may also have to raise the maxval min level in the peak detector. I will get back shortly.

**Comment by jontio** [comment]
Interesting.

Whatever scaling of the soft bits are best depends on the nominal magnitude of the constellation. So for it to work best the agc should have settled before the bits are looked at. That means delaying the bits so the agc can settle before applying the correct scaling of the bits. I think that was done in the burst qpsk but I never paid it too much attention when I did it as I used hard decisions and it makes no difference in that situation.

Did you get the forks back to front? Did you mean the MSK burst looks like a two prong fork and the OQPSK looks like a three prong fork?


OQPSK preamble.

If they are different then something that looks for a bident rather than a trident would be more effective.

For one of your 1200bps burst samples I added some AWGN to it until the burst MSK demodulator struggled to detect it.

[1200burst-c-band-low-snr.zip](https://github.com/jeroenbeijer/JAERO/files/1612928/1200burst-c-band-low-snr.zip)

**Comment by jeroenbeijer** [comment]
Got to get some sleep here soon but from what I recall the OQPSK burst detector looks for a Y shape 
image
However in the MSK case the lower half of the Y extend into to the top part, making really a trident I guess. Anyhow, been a while since I looked at this so I don't recall exactly.  Will try the sample mp2 tomorrow. I added code to pickup the datacd signal in the burst mskdemodulator, this works fine. I increased the threshold but this does not seem to have a noticeable affect.

**Comment by jeroenbeijer** [comment]
So to explain this I ran a clean alternating 0-1 600bps MSK signal through an FFT without squaring the baseband. The resulting  looks like this:

image

So the center frequency is dominant in the result even if the generated signal alternates strictly between the low and high frequency. All 3 frequencies are clearly visible. In the OQPSK burst preamble 0-1 alternating phase one does not see a center peak but only the two top/bottom peaks. hence one can look for the Y shape by subtracting the first "tone" part of the preable from the latter 0-1 part.

In any case this part seems to be working ok, it triggers when needed, I just had to modify the detector to take this into account.

**Comment by jeroenbeijer** [comment]
I looked at the sample, it was in stereo and I have not added handling for this. I realize some folks use the x2 option for 10.5k but since the introduction of the -s switch and the ability to create multiple VFO's in SDR# and SDR Console I personally prefer to just create a separate virtual audio cable for each instance.  it can easily be added though if needed. 

After converting it to mono the application did pick up the burst but half the SU's failed. I tinkered with the soft fec multiplier a little and saw a marginal improvement when using 1.1 but it is hard to tell. 

However I looked at one other aspect that I never quite concluded fully satisfactory is the calculation of the vol_gain variable that is set after the burst detector is triggered. I currently have this as follows:

vol_gain=1.4142*(500.0/(minval/3));

Now the minval values differ dramatically between the 10.5k bursts and MSK 1200 bursts so I divided the minval value to get to a similar level. Now for the sample you created with noise this works perfectly fine if I increase the "divide by" factor to 5. However I am not sure this affects the ultimate value of the soft symbols since another AGC is applied after this. But it does have a significant impact on the initial phase setting logic. I found that the symboltone_pt variable that drives the symboltone rotation is affected by this vol_gain quite a bit. What seems to happen in some cases is that the symboltone_pt rotation in fails to go full circle in phase and thus causes the pll that follows it to not complete a full cycle either. This results in the symbol timing oscillator in not going a full cycle either and hence it does not pass point "ee" and a sample is never taken which causes the phase and frequency correction code to not get executed.

Long story but I hope you get my drift. I can try and visualize this when I have more time in the weekend. But the bottomline is that I think performance can be improved by setting this vol_gain more correctly. 

Note that other samples work better with a divide by "3" vol_gain. 3 roughly seems to give the best results.

Hope you followed all that :-)

**Pull request merged**
